### ISSUE TITLE
Need help for adding on-device recommendation model

### ISSUE THREAD

**Issue by zhuzilin** [margaretmz/awesome-tensorflow-lite#28]
Hi there! I have implemented the [iOS version](https://github.com/zhuzilin/on-device_recommendation_tflite) of the [On-device recommendation](https://github.com/tensorflow/examples/tree/master/lite/examples/recommendation/android) app and I hope to contribute it to this project. Also, there is [an offical blog](https://blog.tensorflow.org/2020/09/introduction-to-tflite-on-device-recommendation.html) about it. Shall I add my implementation along with the official android one to the "What is new" section or add a new section for recommendation?

**Comment by margaretmz** [comment]
Thanks for contributing! Feel free to Add a new section "Recommendation" below "Speech". We can always arrange it later if needed.

OK to put your sample together with the tf.org sample on the same row and also please include the link to the official blog. 
See other entries with "tf.org & Community" as reference on formatting.

**Comment by margaretmz** [comment]
PR #29 merged.
